version: '3.8'
services:
  traefik:
    image: traefik:v3.1
    container_name: Traefik
    restart: unless-stopped
    command:
      - --providers.docker=true
      - --providers.docker.exposedbydefault=false
      - --entrypoints.http.address=:80
      - --entrypoints.https.address=:443
      - --certificatesresolvers.le.acme.httpchallenge=true
      - --certificatesresolvers.le.acme.httpchallenge.entrypoint=http
      - --certificatesresolvers.le.acme.email=mattiastettler@bluewin.ch
      - --certificatesresolvers.le.acme.storage=/acme.json
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./acme.json:/acme.json
#      resources:
#        limits:
#          memory: 80M

  app:
    build:
      context: .
      dockerfile: client/Dockerfile
    container_name: NodeApp
    env_file:
      - ./server/.env
    labels:
      - traefik.enable=true
      - traefik.http.routers.app.rule=Host(`mattia.gr`) || Host(`www.mattia.gr`)
      - traefik.http.routers.app.entrypoints=https
      - traefik.http.routers.app.tls.certresolver=le
      - traefik.http.services.app.loadbalancer.server.port=5000
    depends_on:
      - db
#    deploy:
#      resources:
#        limits:
#          memory: 400M
#          cpus: '1.0'

  db:
    image: postgres:16
    container_name: RecipesDB
    env_file:
      - ./server/.env
    volumes:
      - pgdata:/var/lib/postgresql/data
    command: >
      postgres
      -c shared_buffers=64MB
      -c effective_cache_size=128MB
      -c work_mem=2MB
      -c max_connections=40
    ports:
      - "5432:5432"
#    deploy:
#      resources:
#        limits:
#          memory: 280M

volumes:
  pgdata:
  traefik-acme:
